name: Feature request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature, UX, and any alternatives considered.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / constraints
      description: Privacy requirements, providers, platforms, etc.
      placeholder: |
        - Must support local-only mode
        - Text models only
        - Works with OpenAI-compatible endpoints
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What must be true for this to be considered done?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

